"""Writes src/bus_table.h: every audio bus in the game's Init.bnk (id, parent, name),
for the level meter's per-bus readings.

usage: python tools/bus_table.py <Init_dump.txt> > src/bus_table.h
The dump is wwiser's text dump of Init.bnk (extracted from the game's paks).
"""
import re
import sys

lines = open(sys.argv[1], encoding='utf-8', errors='replace').read().splitlines()
buses = []
for i, line in enumerate(lines):
    if 'eHircType = 0x08 [Audio Bus]' not in line:
        continue
    m = re.search(r'ulID = (\d+)(?: \((.*)\))?', lines[i + 2])
    p = re.search(r'OverrideBusId = (\d+)', lines[i + 4])
    if not m or not p:
        sys.exit(f'unexpected layout at line {i + 1}')
    buses.append((int(m.group(1)), int(p.group(1)), m.group(2) or ''))
ids = {b[0] for b in buses}
for b in buses:
    if b[1] and b[1] not in ids:
        sys.exit(f'bus {b[0]}: parent {b[1]} not in the bank')

print('/* Generated by tools/bus_table.py from the game\'s Init.bnk: every audio bus,')
print(' * with its parent (0 = top level) and name ("" where the bank has none). */')
print('static const struct { uint32_t id, parent; const char *name; } k_buses[] = {')
for bid, parent, name in buses:
    print(f'    {{ {bid}u, {parent}u, "{name}" }},')
print('};')
print(f'#define N_BUSES {len(buses)}')
