"""Build src/dialogue_table.h: the Speech.bnk attenuations Dialogue=positional rewrites.

usage: python tools/dialogue_table.py <the game's Speech.bnk> <its wwiser txt dump>
  The bank comes from the game's paks; the dump from
  `python wwiser.pyz -d txt Speech.bnk` (for which sounds use which attenuation).
  Run it after a game update that changes the dialogue, then rebuild.

An attenuation is rewritten when at least one positioned (3D) sound uses it;
ones used only by unpositioned sounds or by nothing are left alone. Each entry
carries the item's size and an FNV-1a hash of its body, so the mod changes
only the exact bytes this was built from.
"""
import struct, re, collections, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
if len(sys.argv) < 3:
    sys.exit(__doc__)
bank = open(sys.argv[1], "rb").read()

def fnv1a(b):
    h = 2166136261
    for c in b: h = ((h ^ c) * 16777619) & 0xffffffff
    return h

# raw HIRC walk
o, items = 0, {}
while o < len(bank):
    tag, sz = bank[o:o + 4], struct.unpack_from("<I", bank, o + 4)[0]
    if tag == b"HIRC":
        n = struct.unpack_from("<I", bank, o + 8)[0]
        p = o + 12
        for _ in range(n):
            t, isz = bank[p], struct.unpack_from("<I", bank, p + 1)[0]
            body = bank[p + 5:p + 5 + isz]
            if t == 0x0E: items[struct.unpack_from("<I", body, 0)[0]] = body
            p += 5 + isz
    o += 8 + sz

# who uses what (from the dump)
L = open(sys.argv[2], encoding="utf-8", errors="replace").read().splitlines()
objs, cur = [], None
for ln in L:
    m = re.match(r"^ {19}obj  (CAk\w+)\[\d+\]", ln)
    if m: cur = {"t": m.group(1), "l": []}; objs.append(cur); continue
    if cur: cur["l"].append(ln)
byid = {}
for x in objs:
    for ln in x["l"]:
        m = re.search(r"sid  ulID = (\d+)", ln)
        if m: x["id"] = int(m.group(1)); byid[x["id"]] = x; break
def val(x, p):
    for ln in x["l"]:
        m = re.search(p, ln)
        if m: return m.group(1)
def prop(x, name):
    for i, l in enumerate(x["l"]):
        if f"[{name}]" in l and "pID" in l:
            m = re.search(r"pValue = (\S+)", x["l"][i + 1]); return m.group(1) if m else None
def eff(x, key):
    while x:
        if key == "att":
            v = prop(x, "AttenuationID")
            if v: return int(v)
        elif val(x, r"bPositioningInfoOverrideParent = (\d)") == "1":
            return val(x, r"eSpatializationMode = \d \[(\w+)\]")
        p = val(x, r"DirectParentID = (\d+)"); x = byid.get(int(p)) if p else None
use = collections.defaultdict(collections.Counter)
for x in objs:
    if x["t"] == "CAkSound":
        a = eff(x, "att")
        if a: use[a][eff(x, "spat")] += 1

rows = []
for aid, body in sorted(items.items()):
    u = use[aid]
    positioned = u["PositionOnly"] + u["PositionAndOrientation"]
    if not positioned: continue
    # the shape src/dialogue.c understands: cone off, a dry-volume curve and a spread curve
    assert body[5] == 0, f"{aid}: cone enabled"
    ctu = list(struct.unpack_from("<7b", body, 6))
    assert ctu[0] >= 0 and ctu[5] >= 0 and body[13] <= 16, f"{aid}: slots {ctu}, {body[13]} curves"
    rows.append((aid, len(body), fnv1a(body), positioned, sum(u.values()) - positioned))
with open(os.path.join(HERE, "..", "src", "dialogue_table.h"), "w", newline="\n") as f:
    f.write("/* Generated by tools/dialogue_table.py from the game's Speech.bnk (bank version %d).\n"
            % struct.unpack_from("<I", bank, 8)[0])
    f.write(" * The attenuations the dialogue patch rewrites: every one used by a positioned\n"
            " * dialogue sound. id, body size, FNV-1a of the body (positioned / other users). */\n")
    f.write("typedef struct { uint32_t id, size, hash; } dp_att_t;\n")
    f.write("static const dp_att_t k_dp_atts[%d] = {\n" % len(rows))
    for aid, sz, h, p, other in rows:
        f.write("    { %10uu, %3u, 0x%08xu },   /* %d positioned, %d other */\n" % (aid, sz, h, p, other))
    f.write("};\n")
print(len(rows), "attenuations; skipped", len(items) - len(rows))
