/* Generated by tools/dialogue_table.py from the game's Speech.bnk (bank version 140).
 * The attenuations the dialogue patch rewrites: every one used by a positioned
 * dialogue sound. id, body size, FNV-1a of the body (positioned / other users). */
typedef struct { uint32_t id, size, hash; } dp_att_t;
static const dp_att_t k_dp_atts[32] = {
    {   24824021u,  97, 0x57083bfeu },   /* 2 positioned, 0 other */
    {  189472901u, 118, 0x2abdd184u },   /* 1 positioned, 0 other */
    {  196239411u,  97, 0xca13b478u },   /* 2 positioned, 0 other */
    {  251676719u,  82, 0x482af82au },   /* 1 positioned, 0 other */
    {  264660793u, 118, 0xe087a067u },   /* 1 positioned, 0 other */
    {  284122444u, 118, 0x09cc2a60u },   /* 5 positioned, 0 other */
    {  338632003u,  82, 0x5788baa5u },   /* 15 positioned, 0 other */
    {  339690884u,  82, 0x0b0263aeu },   /* 2 positioned, 0 other */
    {  345653707u,  82, 0x34ee3baeu },   /* 25 positioned, 0 other */
    {  351181848u, 145, 0x063f1d26u },   /* 1 positioned, 0 other */
    {  436490261u, 118, 0x389bc7d7u },   /* 2 positioned, 0 other */
    {  458400051u, 118, 0x424410bbu },   /* 1 positioned, 0 other */
    {  500989596u, 130, 0x19bc32c7u },   /* 1 positioned, 0 other */
    {  517111317u,  82, 0x128b02ebu },   /* 1 positioned, 0 other */
    {  589615213u, 118, 0x2f697c4au },   /* 1 positioned, 0 other */
    {  660557895u, 118, 0xdf4f7aceu },   /* 1 positioned, 0 other */
    {  691922709u,  82, 0x7d147b88u },   /* 1 positioned, 0 other */
    {  710865890u,  82, 0x7cf8a203u },   /* 1 positioned, 0 other */
    {  752716305u, 118, 0x46ac4cffu },   /* 5 positioned, 0 other */
    {  784555057u,  70, 0xd1f6a001u },   /* 1 positioned, 0 other */
    {  800082585u,  82, 0x66dba0edu },   /* 3 positioned, 0 other */
    {  843076984u, 142, 0xe2325e7au },   /* 1 positioned, 0 other */
    {  860042507u,  82, 0x14bb9480u },   /* 1 positioned, 0 other */
    {  863852533u, 118, 0xe5ee1431u },   /* 2681 positioned, 30 other */
    {  915114674u, 118, 0x704660feu },   /* 2 positioned, 0 other */
    {  916012099u,  97, 0x39ce8533u },   /* 1 positioned, 0 other */
    {  970680662u,  70, 0x50d87f3bu },   /* 2 positioned, 0 other */
    {  980603374u,  82, 0xa27cf043u },   /* 74 positioned, 1 other */
    { 1001526021u,  94, 0x940538b1u },   /* 4 positioned, 0 other */
    { 1021170851u,  82, 0x25049aebu },   /* 15 positioned, 0 other */
    { 1055506212u, 118, 0x39128fc6u },   /* 1 positioned, 0 other */
    { 1062119803u, 118, 0xfa6e9a17u },   /* 1 positioned, 0 other */
};
